### ISSUE TITLE
Ошибка отправки тега 1256...

### ISSUE THREAD

**Issue by GitMadlab** [andrei-karpov/1c_kkt_54fz#10]
Добрый день.
При печати чека из документа реализации возникает ошибка:
"33h. Ошибка отправки тега 1256: Некорректные параметры в команде."

**Comment by andrei-karpov** [comment]
тег 1256 - это сведения о покупателе, проверяйте, что заполнение в поле  покупатель и его ИНН

**Comment by GitMadlab** [comment]
У контрагента все поля заполнены.
Так тоже пробовали:
ОсновнаяОбработка.мОбщиеПараметры.Вставить("Получатель", "Иванов");
ОсновнаяОбработка.мОбщиеПараметры.Вставить("ПолучательИНН", "813514937282");

**Comment by andrei-karpov** [comment]
Нужен XML файл, что передается на фискальный регистратор, его можно посмотреть, если включить логирование в программе

**Comment by GitMadlab** [comment]
Вот:
[https://drive.google.com/file/d/1k8wXOTMPvVnkeDlRclOPuZBMV_oBm3PZ/view?usp=sharing](url)

**Comment by andrei-karpov** [comment]
Удалите адрес и обновите обработку

**Comment by GitMadlab** [comment]
Адрес покупателя? Я пробовал по-всякому...
https://drive.google.com/file/d/1Cj7uPpqR0h4pyVy09b8_mmeAT9WUyRoh/view?usp=sharing

**Comment by andrei-karpov** [comment]
А если полностью убрать данные покупателя?

**Comment by GitMadlab** [comment]
Снял галку "Печатать данные покупателя" - отработало без ошибок.
https://drive.google.com/file/d/1UfZ7HjZD7f80kiBau_2dhioIQ4qVLVgg/view?usp=sharing

К сожалению пока не могу проверить дальше (на других документах). Закончился демо-режим)))
Эта же ошибка возникала на ПКО и Приход безналичных...
На ЧекеККМ все Ок.

**Comment by sn8sn** [comment]
Столкнулся с той же проблемой, в ФФД 1.1 и 1.2, кроме ИНН обязательны дата рождения и вроде паспорт (подробностей уже не помню, т.к. доп. информация отсутствует в базе) поэтому приходится снимать галку "Печатать данные покупателя". тем более это требуется только в определённых законом случаях, что к нам не применимо
