### ISSUE TITLE
Розница 2.3.10.35

### ISSUE THREAD

**Issue by GitMadlab** [andrei-karpov/1c_kkt_54fz#12]
Добрый день, Андрей.
При подключении эмулятора к Розница 2.3.10.35 последняя ругается на отсутствие в архиве драйвера файла MANIFEST.XML
Обмануть систему, подсунув сторонний файл, у меня не получилось.

Простите, не туда написал. Это к эмулятору...:)

**Comment by andrei-karpov** [comment]
Здравствуйте, потому что версия на гитхаб предназначено для Розницы 2.9 и ниже, так как там другой механизм подключения торгового оборудования.
