### ISSUE TITLE
не полностью очищает при нажатии "снять признак маркированный"

### ISSUE THREAD

**Issue by MihailEv** [andrei-karpov/1c_kkt_54fz#16]
Здравствуйте. Вот что заметил. Когда при закрытии чека открывается окно "ввод маркировок", в этом окне есть кнопка "снять признак маркированный". При нажатии на эту кнопку, происходит очищение всех полей кроме "ДополнительныйРеквизит". Т.е. при нажатии на кнопку "снять признак маркированный" очистится все поля, но в чеке всё равно будет дополнительный реквизит "mrk&". Как его тоже очистить?

**Comment by andrei-karpov** [comment]
Исправлено в релизе 3.7.7
