### ISSUE TITLE
Разработка поддерживается?

### ISSUE THREAD

**Issue by Mikle61** [andrei-karpov/1c_kkt_54fz#17]
Много лет пользуюсь данной разработкой. Нашел ее , оплачивал и скачивал с Инфостарта.
В последнее время на Инфостарте эта разработка явно тормознулась - тех поддержка практически не отвечала.
А тут недавно она просто пропала с Инфостарта.

Вопрос: автор совершенно забросил данную разработку?

Прошу ответить: надо определяться что же делать дальше и стоит ли уже начать искать что-то другое?

**Comment by oshiva7** [comment]
Присоединяюсь к данному вопросу.

**Comment by JMidgard** [comment]
> Много лет пользуюсь данной разработкой. Нашел ее , оплачивал и скачивал с Инфостарта. В последнее время на Инфостарте эта разработка явно тормознулась - тех поддержка практически не отвечала. А тут недавно она просто пропала с Инфостарта.
> 
> Вопрос: автор совершенно забросил данную разработку?
> 
> Прошу ответить: надо определяться что же делать дальше и стоит ли уже начать искать что-то другое?

Я в итоге тоже долго искал эту обработку, оказалось она чутка переехала  https://infostart.ru/marketplace/590993  Последняя версия 3.7.3 и 3.7.5 beta Поддержка ФФД 1.2 реализована. Приобрёл продление по ссылке выше.

**Comment by oshiva7** [comment]
> > Много лет пользуюсь данной разработкой. Нашел ее , оплачивал и скачивал с Инфостарта. В последнее время на Инфостарте эта разработка явно тормознулась - тех поддержка практически не отвечала. А тут недавно она просто пропала с Инфостарта.
> > Вопрос: автор совершенно забросил данную разработку?
> > Прошу ответить: надо определяться что же делать дальше и стоит ли уже начать искать что-то другое?
> 
> Я в итоге тоже долго искал эту обработку, оказалось она чутка переехала https://infostart.ru/marketplace/590993 Последняя версия 3.7.3 и 3.7.5 beta Поддержка ФФД 1.2 реализована. Приобрёл продление по ссылке выше.

Спасибо за комментарий. Я уже успел купить вот такой аналог https://infostart.ru/marketplace/345395/. Поддержка отвечает быстро, есть некоторые отличия, в чем-то даже удобнее.

**Comment by JMidgard** [comment]
> > > Много лет пользуюсь данной разработкой. Нашел ее , оплачивал и скачивал с Инфостарта. В последнее время на Инфостарте эта разработка явно тормознулась - тех поддержка практически не отвечала. А тут недавно она просто пропала с Инфостарта.
> > > Вопрос: автор совершенно забросил данную разработку?
> > > Прошу ответить: надо определяться что же делать дальше и стоит ли уже начать искать что-то другое?
> > 
> > 
> > Я в итоге тоже долго искал эту обработку, оказалось она чутка переехала https://infostart.ru/marketplace/590993 Последняя версия 3.7.3 и 3.7.5 beta Поддержка ФФД 1.2 реализована. Приобрёл продление по ссылке выше.
> 
> Спасибо за комментарий. Я уже успел купить вот такой аналог https://infostart.ru/marketplace/345395/. Поддержка отвечает быстро, есть некоторые отличия, в чем-то даже удобнее.

Спасибо и вам за ссылку, посмотрю сегодня. С поддержкой согласен, не оперативная от слова совсем, но разработчик очень сильный, надеюсь у него всё хорошо.

**Comment by Mikle61** [comment]
> Я в итоге тоже долго искал эту обработку, оказалось она чутка переехала https://infostart.ru/marketplace/590993 Последняя версия 3.7.3 и 3.7.5 beta Поддержка ФФД 1.2 реализована. Приобрёл продление по ссылке выше.

Да, спасибо, это она. Правда поддержка как всегда не отвечает на вопросы....
Я контактировал с администрацией Инфостарта когда они старую публикацию убрали в модерацию - они говорили, что не могут связаться с разработчиком, по этому блокируют ее. А во то, что они ее возобновили по другому адресу - сообщить не удосужились.

**Comment by JMidgard** [comment]
> > Я в итоге тоже долго искал эту обработку, оказалось она чутка переехала https://infostart.ru/marketplace/590993 Последняя версия 3.7.3 и 3.7.5 beta Поддержка ФФД 1.2 реализована. Приобрёл продление по ссылке выше.
> 
> Да, спасибо, это она. Правда поддержка как всегда не отвечает на вопросы.... Я контактировал с администрацией Инфостарта когда они старую публикацию убрали в модерацию - они говорили, что не могут связаться с разработчиком, по этому блокируют ее. А во то, что они ее возобновили по другому адресу - сообщить не удосужились.

Вы не поверите, но мне вчера ответил сам разработчик, правда достучались к нему видимо с ИнфоСтарта. Мне нужно было лицензию активировать. Сейчас появились вопросы по обработке, но как их решать буду пока не знаю)

**Comment by andrei-karpov** [comment]
Приветствую, были проблемы со здоровьем, поэтому такой длительный перерыв, сейчас восстанавливаю работу программы, благо изменений законодательства не сильно много. Пока не на все обращения ответил на почте, и на инфостарте, начну постепенно все обрабатывать.

**Comment by andrei-karpov** [comment]
Подтверждаю, что поддержка ведется, но пока не в том темпе как хотелось бы.

**Comment by JMidgard** [comment]
> Подтверждаю, что поддержка ведется, но пока не в том темпе как хотелось бы.

Отличная новость, Андрей! Рад, что с вами всё хорошо! Вы просто находка для сообщества любителей дописанных конфигурации и не только)  Успехов, здоровья и дальнейшего развития!

**Comment by Mikle61** [comment]
Андрей, Здоровья Вам! Как то по вреиени это совпало с февральскими событиями прошлого года - вызвало волнение. Очень рад, что вы снова в седле!
