### ISSUE TITLE
Хотел приобрести лицензию.

### ISSUE THREAD

**Issue by slava156** [andrei-karpov/1c_kkt_54fz#18]
Добрый день. Приобретал лицензии на инфостарте. Сейчас там обработки нет, какие еще способы есть купить? на почту вы не отвечаете. Как связаться?

**Comment by JMidgard** [comment]
> Добрый день. Приобретал лицензии на инфостарте. Сейчас там обработки нет, какие еще способы есть купить? на почту вы не отвечаете. Как связаться?

Если вдруг ещё ищете она тут https://infostart.ru/marketplace/590993
