### ISSUE TITLE
ошибка при попытке получения ключа или запроса количества доступных лицензий

### ISSUE THREAD

**Issue by reruraturn** [andrei-karpov/1c_kkt_54fz#19]
письма в поддержку тоже не отправляет. пароль не получает. интернет есть.
версия 3.47
текст ошибки: Ошибка при отправке и получении результата запроса: Ошибка при вызове метода контекста (Send): Произошла исключительная ситуация (WinHttp.WinHttpRequest): Время ожидания операции истекло

**Comment by andrei-karpov** [comment]
Здравствуйте. перезагрузил сервер, должно заработать.
