### ISSUE TITLE
марки не проходят проверку

### ISSUE THREAD

**Issue by skreol** [andrei-karpov/1c_kkt_54fz#21]
я видел что была такая же тема но тем не менее не могу понять что не так сделано. уже проковырялись до похожей темы. кассу пересоздал. для проверки маркированного товара используем механизм реализации там есть блок проверить маркировку после этого уже отправляем печатать чек для выведения код через кассу. скрины настроек и лог кассы прилагаю.
[Log54FZ_24_07_2024.txt](https://github.com/user-attachments/files/16363155/Log54FZ_24_07_2024.txt)
![настройки маркировки](https://github.com/user-attachments/assets/798f6965-5a9c-4b56-84fb-9b83ad38e504)
![настройки оборудования](https://github.com/user-attachments/assets/362311fa-6a07-4c54-a2f4-1d25a1904fff)
![ошибка вернувшаяся в 1с](https://github.com/user-attachments/assets/ebd9f22b-1774-49f0-a65d-1f185e901e34)

**Comment by andrei-karpov** [comment]
нет, у вас не такая же ошибка, судя по логу у вас не запускается проверка маркировки, а просто передается информация в чек, вы 1С перезапускали после настройки маркировки?

**Comment by andrei-karpov** [comment]
а здесь, что размещено? "T_ПутьДоДоработки":"K:\\KKT.epf",

**Comment by skreol** [comment]
1с перезапускали. Это на основе вашей обработки изменения внесены чтоб у меня бились чеки с теми реквизитами что нужны в части оплаты. Делал программист сказал что на работу чека реализации повлиять не должно

**Comment by skreol** [comment]
Еще раз до этого было сделано так что в документе реализации провеоялксь корректность маркировки и если все ок да вся инфа передается сразу на ккт и после этого касса бьет чек зачета аванса маркированного товара и таким образом товар сразу же выводиться из оборота. Схема работы у нас осталась таже. Надо как то по другому работать?

**Comment by skreol** [comment]
Эту обработку если есть необходимость могу предоставить

**Comment by andrei-karpov** [comment]
Просто отключите эту обработку, и проверяйте работу без нее, очистите путь к доработкам
логика работы должна быть такая, что перед фискализацией должно запускаться окно проверки маркировки, и это видно по логу, там пишется нужная информация, о том прошла маркировка проверку или нет, у вас этого нет, да и ошибка означает как раз то, что у вас пропущен момент проверки марки, сразу сформирован чек.

**Comment by skreol** [comment]
Ну окей если оно так даже заработает мне помимо маркировки надо чтоб чеки остальные бились так как мне надо а это в логику вашей стандартной обработки не укладывается и что делать? Программист все делал согласно вашим же мануалам как я понимаю ну других то нету. Тогда к вам вопрос в какой момент вызывается эта обработка и на какое событие реагирует

**Comment by skreol** [comment]
Потому что сейчас при нажатии пробить чек выходит окно уже вашей обработки и при нажатии на конпку далее касса нас радостно отправляет в закат бабочек ловить

**Comment by andrei-karpov** [comment]
да мне все равно, как у вас там доработано, моя задача, чтобы заработал стандартный функционал

**Comment by lexlaw2** [comment]
> Нет хорошо сегодня проверим ваше предположение про отключение доработки что будет в результате я вам отпишу

используем эту обработку с начала 54фз, возможно смогу вам помочь  ... ну так просто интересно)
https://t.me/lexlaw2

**Comment by andrei-karpov** [comment]
@skreol у вас получилось пробить чек с маркировкой?

**Comment by skreol** [comment]
добрый и так итог мучений и поисков. во первых немного перемудрили в реализации не нужно было ставить аванс как предмет расчета. поэтому проверка даже не вызывалось на что вы как разработчик могли и указать. путем переговоров с автором такой же темы установил драйвер ккт 10.9.4.5 итогом получил вот такую картину
![итог мучений](https://github.com/user-attachments/assets/39cf30b9-870c-4658-b416-c205ad7277c1)
[Log54FZ_26_07_2024.txt](https://github.com/user-attachments/files/16387486/Log54FZ_26_07_2024.txt)
очень бы хотелось ваших комментариев и путь решения. подмена на ваши старые макеты не помогает 1с говорит что нет обработки для атол. сейчас драйвер атол 10.9.4.5 одни из последних макетов. подмена длл из папки атола тоже не дает результата в виде М+ в проверке

**Comment by andrei-karpov** [comment]
Значит так, если вы не прекратите разговаривать со мной в "обвинительной" манере, то не получите никакой консультации, тем более техническая поддержка у вас закончилась уже 2 месяца назад.
если же готовы нормально пообщаться, то нужно проверить 3 момента: 
- связь с сервером маркировки (ИСМ), например по этой инструкции https://atol-kassa.ru/atol-kkm-proverit-svyaz-s-ism-informaczionnaya-sistema-markirovki/ 
- также уточнить, какую именно маркировку сканируете, и что именно попадает в окно маркировки, для этого в параметрах обработки в разделе "Исправление ошибок", поставьте флажок "Логировать код маркировки", и пришлите фото этой маркировки.
- проверить, а доступна ли вообще маркировка, так как АТОЛ функционал маркировки продает за отдельной лицензией, плюс при регистрации ККТ нужно указать продажу маркированного товара (возможно требуется перерегистрация).

**Comment by andrei-karpov** [comment]
Плюс я бы проверил, а открыта ли у вас кассовая смена?

**Comment by skreol** [comment]
кассовая смена была открыта
![проверка2](https://github.com/user-attachments/assets/4ecef8d0-1366-4111-bb5b-e61bd96e1c52)
лог кассы без обработки
[Log54FZ_29_07_2024.txt](https://github.com/user-attachments/files/16418263/Log54FZ_29_07_2024.txt)
очень смущает вот эта часть лога fptr1C.log
2024.07.29 10:04:24.248 T:      T:00011B58 INFO  [1C] ЗапросКМ - [<?xml version="1.0" encoding="UTF-8"?>
<RequestKM GUID="8c319c6f-16d7-43f0-b4bd-f60bdb11fdbf" MarkingCode="MDExKTA0NjIwMDcwMjMwNzIxKDIxKTVzcmwnVWZsWA==" PlannedStatus="1"/>]
2024.07.29 10:04:24.521 T:      T:00011B58 INFO  [1C] РезультатЗапросаКМ - [<?xml version="1.0" encoding="UTF-8"?>
<RequestKMResult Checking="False" CheckingResult="False"/>
]
код маркировки который передает 1с в кассу как я понимаю либо не полный либо как то не правильно интерпретируется
код маркировки проверял так же через тест кассы ошибка та же самая
![проверка ккт](https://github.com/user-attachments/assets/4c7751f0-0bf7-4db9-b2bd-0ab3093171f4)
5 | Проверка КП КМ выполнена с отрицательным результатом, статус товара у ОИСМ некорректен

**Comment by skreol** [comment]
также уточнить, какую именно маркировку сканируете, и что именно попадает в окно маркировки, для этого в параметрах обработки в разделе "Исправление ошибок", поставьте флажок "Записывать информацию по маркировки в лог", перезапустите 1С и пришлите фото этой маркировки.
данный пункт не очень понял обычный qr код предоставленный производителем. тип маркировки если имеется ввиду то легкая промышленность. что именно проверяет 1с я написал. облазил всю обработку раздела исправления ошибок не нашел может не там искал?

**Comment by andrei-karpov** [comment]
У вас на картинке не хватает криптохвоста https://dzen.ru/a/ZX12Tmf4gTNsqFs4 , начинающийся с тега 91, марка должна быть длиннее.
То что вы проверяете через тест драйвера ФР, там должна быть другая марка, вы берете марку в формате base64, которую формирует обработка, она формируется на основании обычной марки, и используется специально для передачи на кассу, чтобы сохранить все нужные символы маркировки, через тест драйвера нужно проверять обычную марку, как она отсканирована.
Как я это вижу, и судя по вашим данным, марка уже находится на учете, и занесена 1С, при продаже она подтягивается из документа реализации, однако марка оприходована без полного кода, (полный код марки хранится в регистре "пул кодов маркировки"), и при попадании в обработку она также проверяется без криптохвоста, отсюда и ошибка. 
Для чистоты эксперимента, вам нужно сканировать маркировку прямо в окне проверки печати обработки. для этого можно нажать кнопку F7 или нажать на кнопку штрихкода. и отсканировать марку заново, тогда на кассу попадет полная марка. ![image](https://github.com/user-attachments/assets/d0d5dcf6-ac5b-4751-8597-ae69d5b71f9f)
Раздел "исправление ошибок" - 
![Uploading image.png…]()

также я обратил внимание, что у вас ранее в поле "Ревизия", было 3004, однако сейчас 4000, это значит, что у вас возможно подключено 2 оборудования на одну кассу, и компоненты конфликтуют, проверьте, чтобы проверка шла для одной кассы.
