### ISSUE TITLE
Orange Data

### ISSUE THREAD

**Issue by Makcum32** [andrei-karpov/1c_kkt_54fz#5]
Добрый день.
Подскажите пожалуйста как правильно настроить обработку для работы через Orange Data
(УТ 10.3
![image](https://user-images.githubusercontent.com/66387799/121596507-290b6200-ca48-11eb-89ec-3b4140f419a2.png)
![image](https://user-images.githubusercontent.com/66387799/121596565-417b7c80-ca48-11eb-8caa-6783ccea4f82.png)
![image](https://user-images.githubusercontent.com/66387799/121596717-7d164680-ca48-11eb-8806-d910560c38b1.png)

**Comment by andrei-karpov** [comment]
Здравствуйте, ни разу не настраивал orange data, данная возможность идет чисто на стороне компоненты ШтрихМ, в которой и добавлен этот функционал, можно попробовать поискать информацию на официальной страницы Штрих
