### ISSUE TITLE
виртуальная касса - Нельзя подключаться к уже подключенному оборудованию

### ISSUE THREAD

**Issue by lexlaw2** [andrei-karpov/1c_kkt_54fz#6]
после установки обработки версии 3.60 (и 3.62 скачанной с яндекса)
при попытке напечатать чтолибо на виртуальной кассе выдает ошибку
"Нельзя подключаться к уже подключенному оборудованию"
тест устройства проходит нормально
макеты скачаны с яндекса 17.09.21
если подключить макеты 2019 года, то виртуальная касса работает
![image](https://user-images.githubusercontent.com/43840010/133741578-7e5637a8-0a1c-4eff-a5b6-1566383b5f8b.png)
![image](https://user-images.githubusercontent.com/43840010/133741665-24110d37-25f8-4075-9c93-8f4c4cb79d2b.png)
![image](https://user-images.githubusercontent.com/43840010/133742160-d15512ee-087a-47a4-8387-e2296caf8693.png)

мы: system@fregat42.ru

**Comment by lexlaw2** [comment]
возможно проблема связана с тестовой базой запускаемой с этого же компьютера

**Comment by andrei-karpov** [comment]
Видимо какая-то ошибка произошла при подключении к кассе, установите в параметрах программы ругой номер ККТ, тогда подключение будет работать итак

**Comment by andrei-karpov** [comment]
Обновил эмулятор, теперь блокировкой кассы управляет отдельный параметр в настройках эмулятора

**Comment by lexlaw2** [comment]
смена номера ККТ не помогла
обновление обработки и макетов - помогло
спасибо

**Comment by prokhorenkov75-web** [comment]
Версия обработки 4,05
Всё прекрасно работало. Но со вчерашнего дня ошибка "Нельзя подключаться к уже подключенному оборудованию"
И что делать непонятно.
<img width="1486" height="535" alt="Image" src="https://github.com/user-attachments/assets/2a8fbb0e-124a-4844-a1b3-e152253aebc7" />
