### ISSUE TITLE
запрет выбора кассы

### ISSUE THREAD

**Issue by lexlaw2** [andrei-karpov/1c_kkt_54fz#7]
Хотелось бы чтобы кассиры могли печатать только на кассе установленной для них по-умолчанию
и не могли распечатать на чужой кассе
(организация с 2 филиалами и другая организация все работают на одном терминальном сервере, в одной базе,
пользователи не туда тыкнули чек ушел либо в другой город, либо в другую организацию)
хотелось бы увидеть подобный функционал в новых версиях

**Comment by lexlaw2** [comment]
![image](https://user-images.githubusercontent.com/43840010/133745687-7d160618-87c6-451f-9279-be774a9b67bd.png)
![image](https://user-images.githubusercontent.com/43840010/133746847-65bfbbf8-91d4-4674-bb44-b5e8718d824e.png)

хотелось чтоб мне выводились только те кассыККМ, которые сопоставленны с кассой в справочнике пользователи

**Comment by andrei-karpov** [comment]
Здравствуйте, это не функционал обработки, и лучше такое делать в конфигурации, подменить операцию выбора кассы на свой механизм
