### ISSUE TITLE
неточности в документации

### ISSUE THREAD

**Issue by lexlaw2** [andrei-karpov/1c_kkt_54fz#8]
похоже 
## Форма ввода Email и Номера телефона
устарела, в последней версии не смог ее добиться ее вывода

https://github.com/andrei-karpov/1c_kkt_54fz/blob/main/management_distribution.md#%D1%84%D0%BE%D1%80%D0%BC%D0%B0-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0-email-%D0%B8-%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%B0-%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%B0

**Comment by andrei-karpov** [comment]
Форма выводится в том случае, если не открывается форма проверки печати, так в форме проверки печати можно ввести email или номер телефона непосредственно.
