### ISSUE TITLE
Ставка НДС

### ISSUE THREAD

**Issue by GitMadlab** [andrei-karpov/1c_kkt_54fz#9]
Добрый день.
Не могу поменять ставку НДС через процедуру "ПослеФормированииТаблицыЧека".

Делаем, как в документации:

//Удаление НДС из чека
    Для Каждого СтрокаЧека Из пТаблицаЧека Цикл
     СтрокаЧека.СтавкаНДС = "20";
    КонецЦикла;

Значение остается пустым, т.е. ставка НДС не заполнена.

**Comment by andrei-karpov** [comment]
20 - должно быть числом

**Comment by GitMadlab** [comment]
Спасибо.
